### ISSUE TITLE
Change react-native-webview to community

### ISSUE THREAD

**Issue by Gerlison** [Gerlison/git_finder#9]
1. Update lib dependecie
2. Update imports

**Comment by SubhamKarmakar24** [comment]
Can I work on this? @Gerlison

**Comment by Gerlison** [comment]
Sure, I'll analyse all pull requests submitted. Make sure to describe "Fixes #9" on your PR

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Sure, I'll analyse all pull requests submitted. Make sure to describe "Fixes #9" on your PR

Okay. Thanks
